import React, { useState } from 'react';
import { uploadDriveFile } from '../../services/driveService';
import { createGmailDraft } from '../../services/gmailService';
import { AcpService } from '../../services/acpService';

interface CloudSaveModalProps {
  isOpen: boolean;
  onClose: () => void;
  htmlContent: string;
  pageTitle: string;
  prompt?: string;
  onOpenGmailWorkspace?: () => void;
  onOpenDriveWorkspace?: () => void;
}

export const CloudSaveModal: React.FC<CloudSaveModalProps> = ({
  isOpen,
  onClose,
  htmlContent,
  pageTitle,
  prompt,
  onOpenGmailWorkspace,
  onOpenDriveWorkspace,
}) => {
  const [activeDestination, setActiveDestination] = useState<'drive' | 'gmail' | 'acp' | 'download'>('drive');
  const [fileName, setFileName] = useState<string>(() => {
    const sanitized = (pageTitle || 'generated_app')
      .toLowerCase()
      .replace(/[^a-z0-9_-]/g, '_')
      .replace(/_+/g, '_');
    return `${sanitized}.html`;
  });
  const [emailSubject, setEmailSubject] = useState<string>(`Preview: ${pageTitle || 'AgentSam Generated App'}`);
  const [emailRecipient, setEmailRecipient] = useState<string>('');
  const [isSaving, setIsSaving] = useState<boolean>(false);
  const [saveStatus, setSaveStatus] = useState<{
    success: boolean;
    message: string;
    linkUrl?: string;
    destination?: string;
  } | null>(null);

  if (!isOpen) return null;

  const handleSaveToDrive = async () => {
    setIsSaving(true);
    setSaveStatus(null);
    try {
      const file = await uploadDriveFile(fileName, htmlContent, 'text/html');
      setSaveStatus({
        success: true,
        message: `Successfully saved "${file.name}" to Google Drive!`,
        linkUrl: file.webViewLink,
        destination: 'drive',
      });
    } catch (err: any) {
      setSaveStatus({
        success: false,
        message: err.message || 'Failed to save to Google Drive',
      });
    } finally {
      setIsSaving(false);
    }
  };

  const handleDraftToGmail = async () => {
    setIsSaving(true);
    setSaveStatus(null);
    try {
      const draftBody = `
<h3>${pageTitle || 'AgentSam Generated Application'}</h3>
<p>Here is the web application generated by AgentSamAutoBrowserShell.</p>
<hr />
<div><strong>Prompt:</strong> ${prompt || 'Autonomous Generation'}</div>
<div><strong>Date:</strong> ${new Date().toLocaleString()}</div>
<hr />
<p>Full HTML content included below:</p>
<pre style="background:#f4f4f4;padding:12px;border-radius:6px;overflow:auto;max-height:400px;">
${htmlContent.replace(/</g, '&lt;').replace(/>/g, '&gt;')}
</pre>
      `.trim();

      await createGmailDraft({
        to: emailRecipient,
        subject: emailSubject,
        body: draftBody,
        isHtml: true,
      });

      setSaveStatus({
        success: true,
        message: `Draft created in your Gmail account with subject "${emailSubject}"!`,
        destination: 'gmail',
      });
    } catch (err: any) {
      setSaveStatus({
        success: false,
        message: err.message || 'Failed to create Gmail draft',
      });
    } finally {
      setIsSaving(false);
    }
  };

  const handleSaveToAcp = async () => {
    setIsSaving(true);
    setSaveStatus(null);
    try {
      const res = await AcpService.executeTool('file_diff', {
        filePath: `dist/${fileName}`,
        contentLength: htmlContent.length,
        title: pageTitle,
      });
      setSaveStatus({
        success: true,
        message: `Artifact registered with AgentSam ACP Server! (${res.stdout || 'Success'})`,
        destination: 'acp',
      });
    } catch (err: any) {
      setSaveStatus({
        success: false,
        message: err.message || 'Failed to register with ACP Server',
      });
    } finally {
      setIsSaving(false);
    }
  };

  const handleDownloadHtml = () => {
    const blob = new Blob([htmlContent], { type: 'text/html;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = fileName;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    setSaveStatus({
      success: true,
      message: `Downloaded "${fileName}" to your local filesystem.`,
      destination: 'download',
    });
  };

  const handleExecuteSave = () => {
    switch (activeDestination) {
      case 'drive':
        return handleSaveToDrive();
      case 'gmail':
        return handleDraftToGmail();
      case 'acp':
        return handleSaveToAcp();
      case 'download':
        return handleDownloadHtml();
    }
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm flex items-center justify-center p-4">
      <div className="bg-[#0f1422] border border-gray-700/80 rounded-2xl w-full max-w-lg shadow-2xl overflow-hidden flex flex-col text-gray-200">
        {/* Header */}
        <div className="px-5 py-4 border-b border-gray-800 flex items-center justify-between bg-[#121828]">
          <div className="flex items-center gap-2.5">
            <div className="p-2 rounded-lg bg-blue-900/40 text-blue-400 border border-blue-700/50">
              <span className="material-symbols-outlined text-lg">cloud_upload</span>
            </div>
            <div>
              <h3 className="font-bold text-sm text-gray-100">Save to Cloud Connected Resources</h3>
              <p className="text-[11px] text-gray-400">Save generated preview to Google Drive, Gmail, or ACP</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-gray-400 hover:text-gray-200 hover:bg-gray-800 transition-colors"
          >
            <span className="material-symbols-outlined text-lg">close</span>
          </button>
        </div>

        {/* Destination Tabs */}
        <div className="flex border-b border-gray-800 bg-[#0c101a] px-5 pt-3 gap-2">
          <button
            onClick={() => setActiveDestination('drive')}
            className={`pb-2.5 px-3 text-xs font-semibold flex items-center gap-1.5 border-b-2 transition-all ${
              activeDestination === 'drive'
                ? 'border-blue-500 text-blue-400'
                : 'border-transparent text-gray-400 hover:text-gray-200'
            }`}
          >
            <span className="material-symbols-outlined text-sm">cloud</span>
            <span>Google Drive</span>
          </button>

          <button
            onClick={() => setActiveDestination('gmail')}
            className={`pb-2.5 px-3 text-xs font-semibold flex items-center gap-1.5 border-b-2 transition-all ${
              activeDestination === 'gmail'
                ? 'border-rose-500 text-rose-400'
                : 'border-transparent text-gray-400 hover:text-gray-200'
            }`}
          >
            <span className="material-symbols-outlined text-sm">mail</span>
            <span>Gmail Draft</span>
          </button>

          <button
            onClick={() => setActiveDestination('acp')}
            className={`pb-2.5 px-3 text-xs font-semibold flex items-center gap-1.5 border-b-2 transition-all ${
              activeDestination === 'acp'
                ? 'border-purple-500 text-purple-400'
                : 'border-transparent text-gray-400 hover:text-gray-200'
            }`}
          >
            <span className="material-symbols-outlined text-sm">shield</span>
            <span>ACP Artifact</span>
          </button>

          <button
            onClick={() => setActiveDestination('download')}
            className={`pb-2.5 px-3 text-xs font-semibold flex items-center gap-1.5 border-b-2 transition-all ${
              activeDestination === 'download'
                ? 'border-emerald-500 text-emerald-400'
                : 'border-transparent text-gray-400 hover:text-gray-200'
            }`}
          >
            <span className="material-symbols-outlined text-sm">download</span>
            <span>Local HTML</span>
          </button>
        </div>

        {/* Content Body */}
        <div className="p-5 space-y-4 text-xs font-sans">
          {/* File Name input */}
          <div>
            <label className="block text-gray-400 font-medium mb-1.5 text-[11px] uppercase tracking-wider">
              File Name
            </label>
            <input
              type="text"
              value={fileName}
              onChange={e => setFileName(e.target.value)}
              className="w-full bg-gray-950 border border-gray-700/80 rounded-lg px-3 py-2 text-xs text-gray-200 font-mono focus:outline-none focus:border-blue-500"
            />
          </div>

          {/* Drive Specific */}
          {activeDestination === 'drive' && (
            <div className="p-3 rounded-xl border border-blue-900/40 bg-blue-950/20 text-gray-300 space-y-2">
              <div className="flex items-center gap-2 text-blue-300 font-semibold">
                <span className="material-symbols-outlined text-base">cloud_sync</span>
                <span>Direct Google Drive Cloud Upload</span>
              </div>
              <p className="text-[11px] text-gray-400 leading-relaxed">
                Uploads this HTML website directly into your authenticated Google Drive storage. You can view, share, and reload it anytime.
              </p>
            </div>
          )}

          {/* Gmail Specific */}
          {activeDestination === 'gmail' && (
            <div className="space-y-3">
              <div>
                <label className="block text-gray-400 font-medium mb-1 text-[11px] uppercase tracking-wider">
                  Subject Line
                </label>
                <input
                  type="text"
                  value={emailSubject}
                  onChange={e => setEmailSubject(e.target.value)}
                  className="w-full bg-gray-950 border border-gray-700/80 rounded-lg px-3 py-2 text-xs text-gray-200 focus:outline-none focus:border-blue-500"
                />
              </div>

              <div>
                <label className="block text-gray-400 font-medium mb-1 text-[11px] uppercase tracking-wider">
                  Recipient (Optional)
                </label>
                <input
                  type="email"
                  placeholder="collaborator@example.com (leave blank for personal draft)"
                  value={emailRecipient}
                  onChange={e => setEmailRecipient(e.target.value)}
                  className="w-full bg-gray-950 border border-gray-700/80 rounded-lg px-3 py-2 text-xs text-gray-200 focus:outline-none focus:border-blue-500"
                />
              </div>
            </div>
          )}

          {/* ACP Specific */}
          {activeDestination === 'acp' && (
            <div className="p-3 rounded-xl border border-purple-900/40 bg-purple-950/20 text-gray-300 space-y-2">
              <div className="flex items-center gap-2 text-purple-300 font-semibold">
                <span className="material-symbols-outlined text-base">verified</span>
                <span>Agent Client Protocol Snapshot</span>
              </div>
              <p className="text-[11px] text-gray-400 leading-relaxed">
                Registers the preview with the local/remote ACP daemon at <code>/api/agentsam/acp</code>, linking it with your active session audit sequence.
              </p>
            </div>
          )}

          {/* Status Message */}
          {saveStatus && (
            <div
              className={`p-3 rounded-xl border flex items-center justify-between text-xs ${
                saveStatus.success
                  ? 'bg-emerald-950/40 border-emerald-700/60 text-emerald-300'
                  : 'bg-rose-950/40 border-rose-700/60 text-rose-300'
              }`}
            >
              <div className="flex items-center gap-2">
                <span className="material-symbols-outlined text-base">
                  {saveStatus.success ? 'check_circle' : 'error'}
                </span>
                <span>{saveStatus.message}</span>
              </div>

              {saveStatus.linkUrl && (
                <a
                  href={saveStatus.linkUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="px-2 py-1 bg-emerald-800/60 hover:bg-emerald-700/60 text-white rounded font-medium text-[11px] flex items-center gap-1 transition-colors"
                >
                  <span>Open in Drive</span>
                  <span className="material-symbols-outlined text-xs">open_in_new</span>
                </a>
              )}
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="px-5 py-3.5 border-t border-gray-800 bg-[#121828] flex items-center justify-between">
          <div className="flex items-center gap-2 text-xs text-gray-400">
            {saveStatus?.success && activeDestination === 'drive' && onOpenDriveWorkspace && (
              <button
                type="button"
                onClick={() => {
                  onClose();
                  onOpenDriveWorkspace();
                }}
                className="text-blue-400 hover:underline flex items-center gap-1"
              >
                <span>Go to Drive Workspace</span>
                <span className="material-symbols-outlined text-xs">arrow_forward</span>
              </button>
            )}

            {saveStatus?.success && activeDestination === 'gmail' && onOpenGmailWorkspace && (
              <button
                type="button"
                onClick={() => {
                  onClose();
                  onOpenGmailWorkspace();
                }}
                className="text-rose-400 hover:underline flex items-center gap-1"
              >
                <span>Go to Gmail Workspace</span>
                <span className="material-symbols-outlined text-xs">arrow_forward</span>
              </button>
            )}
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={onClose}
              className="px-3.5 py-1.5 rounded-lg border border-gray-700 text-gray-300 hover:bg-gray-800 text-xs font-medium transition-colors"
            >
              Close
            </button>
            <button
              onClick={handleExecuteSave}
              disabled={isSaving}
              className="px-4 py-1.5 rounded-lg bg-blue-600 hover:bg-blue-500 disabled:opacity-50 text-white text-xs font-semibold flex items-center gap-1.5 shadow-md shadow-blue-900/30 transition-all"
            >
              {isSaving && <span className="w-3 h-3 rounded-full border-2 border-white border-t-transparent animate-spin"></span>}
              <span>{isSaving ? 'Saving...' : activeDestination === 'download' ? 'Download HTML' : 'Save to Cloud'}</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
